version: "3.9"

services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  redis:
    container_name: redis
    image: redis:6-alpine
    command: redis-server --requirepass 123456
    ports:
      - "6380:6379"
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    environment:
      - POSTGRES_USER=rciolette
      - POSTGRES_PASSWORD=Raphael106612
      - POSTGRES_DB=evolution
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    driver: bridge